### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by point-4ward** [danielguerra69/alpine-i2pd#1]
Hi,

I can't get this container to work.  I found it whilst experimenting with https://github.com/danielguerra69/deepweb-router and using the docker-compose suggested in the readme.

I can't see any options for it, but after mucking around with the tor bit (which is working perfectly) I spent a while trying to see the i2p side and couldn't get anything.  Went in to logs and when this container fires up the only entry in the logs is:

```
Illegal instruction
Exited with code 132
```

The entry in docker-compose is identical to the one in the readme for deepweb-router, and there doesn't seem to be any extra configuration options here, so I'm stumped.

Any thoughts please?

Thanks

**Comment by danielguerra69** [comment]
I think it needs a fresh rebuild. I'll get back on this.

**Comment by danielguerra69** [comment]
It should be working now, just tested it.

**Comment by danielguerra69** [comment]
You need to do a docker-compose pull

**Comment by point-4ward** [comment]
Ace, thanks for looking into this. I'm unable to test it right now but I will get back to it soon :+1:

Thanks again :slightly_smiling_face:
